// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CineXpress.Model
{
    public partial class Filme
    {
        public Filme()
        {
            Relacional = new HashSet<Relacional>();
        }

        [Key]
        [Column("idfl")]
        public int Idfl { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string NomeFilme { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string Classificação { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Sinopse { get; set; }
        public TimeSpan? Duracao { get; set; }

        [InverseProperty("IdFilmeNavigation")]
        public virtual ICollection<Relacional> Relacional { get; set; }
    }
}