// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CineXpress.Model
{
    public partial class Relacional
    {
        [Column("idFilme")]
        public int? IdFilme { get; set; }
        [Column("idCadastro")]
        public int? IdCadastro { get; set; }
        [Column("idFuncionario")]
        public int? IdFuncionario { get; set; }
        [Key]
        public int IdR { get; set; }

        [ForeignKey("IdCadastro")]
        [InverseProperty("Relacional")]
        public virtual CadastroCliente IdCadastroNavigation { get; set; }
        [ForeignKey("IdFilme")]
        [InverseProperty("Relacional")]
        public virtual Filme IdFilmeNavigation { get; set; }
        [ForeignKey("IdFuncionario")]
        [InverseProperty("Relacional")]
        public virtual CadastroFuncionario IdFuncionarioNavigation { get; set; }
    }
}