// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CineXpress.Model
{
    [Table("tb_Cliente")]
    public partial class TbCliente
    {
        public TbCliente()
        {
            TbRelacional = new HashSet<TbRelacional>();
        }

        [Key]
        [Display(Name = "Código")] // Data Annotation
        public int Id { get; set; }
        [StringLength(50)]
        [Unicode(false)]

        [Display(Name = "Nome")] // Data Annotation
        public string NomeCadastro { get; set; }
        [StringLength(50)]
        [Unicode(false)]

        [Display(Name = "E-Mail")] // Data Annotation
        public string Email { get; set; }
        [StringLength(50)]
        [Unicode(false)]

        public string Senha { get; set; }
        [Column("CPF")]
        [StringLength(15)]
        [Unicode(false)]

        [Display(Name = "CPF")] // Data Annotation
        public string Cpf { get; set; }
        [Column(TypeName = "date")]

        [Display(Name = "Data de nascimento")] // Data Annotation
        public DateTime? DataNascimento { get; set; }
        [StringLength(12)]
        [Unicode(false)]
        public string Celular { get; set; }

        [InverseProperty("IdClienteNavigation")]
        public virtual ICollection<TbRelacional> TbRelacional { get; set; }
    }
}