// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CineXpress.Model
{
    [Table("tb_Filme")]
    public partial class TbFilme
    {
        public TbFilme()
        {
            TbRelacional = new HashSet<TbRelacional>();
        }

        [Key]
        [Display(Name = "Cód. Filme")]
        public int Id { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        [Display(Name = "Título")]
        public string NomeFilme { get; set; }
        
        [StringLength(100)]
        [Unicode(false)]
        [Display(Name = "Sinopse")]
        public string Sinopse { get; set; }
        [Display(Name = "Tempo de duração")]
        public TimeSpan? Duracao { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        [Display(Name = "Classificação")]
        public string Classificacao { get; set; }
        

        [InverseProperty("IdFilmeNavigation")]
        public virtual ICollection<TbRelacional> TbRelacional { get; set; }
    }
}