// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CineXpress.Model
{
    [Table("tb_Filme")]
    public partial class TbFilme
    {
        public TbFilme()
        {
            TbRelacional = new HashSet<TbRelacional>();
        }

        [Key]
        [Column("fil_Id")]
        public int FilId { get; set; }
        [Column("fil_Nome")]
        [StringLength(50)]
        [Unicode(false)]
        public string FilNome { get; set; }
        [Column("fil_Sinopse")]
        [StringLength(100)]
        [Unicode(false)]
        public string FilSinopse { get; set; }
        [Column("fil_Duracao")]
        public TimeSpan? FilDuracao { get; set; }
        [Column("fil_Classificacao")]
        [StringLength(10)]
        [Unicode(false)]
        public string FilClassificacao { get; set; }
        [Column("fil_Link")]
        [StringLength(100)]
        [Unicode(false)]
        public string FilLink { get; set; }

        [InverseProperty("RelIdFilmeNavigation")]
        public virtual ICollection<TbRelacional> TbRelacional { get; set; }
    }
}