// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CineXpress.Model
{
    [Table("tb_Funcionario")]
    public partial class TbFuncionario
    {
        public TbFuncionario()
        {
            TbRelacional = new HashSet<TbRelacional>();
        }

        [Key]
        [Column("fun_Id")]
        public int FunId { get; set; }
        [Column("fun_Nome")]
        [StringLength(50)]
        [Unicode(false)]
        public string FunNome { get; set; }
        [Column("fun_Email")]
        [StringLength(50)]
        [Unicode(false)]
        public string FunEmail { get; set; }
        [Column("fun_Senha")]
        [StringLength(50)]
        [Unicode(false)]
        public string FunSenha { get; set; }
        [Column("fun_CPF")]
        [StringLength(15)]
        [Unicode(false)]
        public string FunCpf { get; set; }
        [Column("fun_DataNascimento", TypeName = "date")]
        public DateTime? FunDataNascimento { get; set; }
        [Column("fun_Celular")]
        [StringLength(12)]
        [Unicode(false)]
        public string FunCelular { get; set; }

        [InverseProperty("RelIdFuncionarioNavigation")]
        public virtual ICollection<TbRelacional> TbRelacional { get; set; }
    }
}