// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CineXpress.Model
{
    [Table("tb_Relacional")]
    public partial class TbRelacional
    {
        [Key]
        [Column("rel_Id")]
        public int RelId { get; set; }
        [Column("rel_idFilme")]
        public int? RelIdFilme { get; set; }
        [Column("rel_idCliente")]
        public int? RelIdCliente { get; set; }
        [Column("rel_idFuncionario")]
        public int? RelIdFuncionario { get; set; }

        [ForeignKey("RelIdCliente")]
        [InverseProperty("TbRelacional")]
        public virtual TbCliente RelIdClienteNavigation { get; set; }
        [ForeignKey("RelIdFilme")]
        [InverseProperty("TbRelacional")]
        public virtual TbFilme RelIdFilmeNavigation { get; set; }
        [ForeignKey("RelIdFuncionario")]
        [InverseProperty("TbRelacional")]
        public virtual TbFuncionario RelIdFuncionarioNavigation { get; set; }
    }
}