// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CineXpress.Model
{
    [Table("tb_Relacional")]
    public partial class TbRelacional
    {
        [Key]
        public int Id { get; set; }
        [Column("idFilme")]
        public int? IdFilme { get; set; }
        [Column("idCliente")]
        public int? IdCliente { get; set; }
        [Column("idFuncionario")]
        public int? IdFuncionario { get; set; }

        [ForeignKey("IdCliente")]
        [InverseProperty("TbRelacional")]
        public virtual TbCliente IdClienteNavigation { get; set; }
        [ForeignKey("IdFilme")]
        [InverseProperty("TbRelacional")]
        public virtual TbFilme IdFilmeNavigation { get; set; }
        [ForeignKey("IdFuncionario")]
        [InverseProperty("TbRelacional")]
        public virtual TbFuncionario IdFuncionarioNavigation { get; set; }
    }
}